name: 'Match PR Label'
description: 'Requires a PR to exactly one of the labels from a list'
inputs:
  allowed:
    description: >
      Comma- or newline-separated label names to match exactly one of.

      Mutually exclusive with `allowed_multiple`.
    required: false
  allowed_multiple:
    description: >
      Comma- or newline-separated label names to match many of'

      Mutually exclusive with `allowed`.
    required: false
  default_match:
    description: Label name to "match" if no matching labels are found
    required: false
outputs:
  match:
    description: 'The matched label, if found. Comma-separated if multiple.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'hash'
  color: 'orange'
